language: php

php:
  - 7.4

env:
  - TRAVIS_RABBIT_MQ_QUEUE=TRUE TRAVIS_TESTS_ENV=TRUE

services:
  - mysql

matrix:
  fast_finish: true

after_failure:
  - for i in $(find log -name \*.log); do echo "--- $i"; cat $i; echo; echo; done

install:
  - cp tests/travis/test.local.neon config/config.local.neon
  - composer install --no-interaction -o
  - mysql -u root -e 'CREATE DATABASE `public-transport-app-test`;'

script:
  - composer migration-migrate
  - composer build-all

cache:
  directories:
    - $HOME/.composer/cache